package com.damon.dao;

import com.damon.pojo.JOrder;

import java.util.List;
import java.util.Map;

public interface JOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order
     *
     * @mbg.generated
     */
    int insert(JOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order
     *
     * @mbg.generated
     */
    int insertSelective(JOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order
     *
     * @mbg.generated
     */
    JOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(JOrder record);

    List<JOrder> listOrder(Map<String, Object> params);

    int batchInsert(List<JOrder> list);
}